Fix substitute when using metadata
JuliaSymbolics/SymbolicUtils.jl pull request #284
Opened 2021-04-19 15:13 UTC by shashi

fixes #283

2021-04-19 15:38 UTC, YingboMa approved these changes

2021-04-19 16:14 UTC, adamslc requested changes
One typo to fix.

2021-04-19 16:14 UTC, adamslc commented on src/types.jl
> +metadata(s::Any) = x
```suggestion
metadata(s::Any) = nothing
```

2021-04-20 02:07 UTC, shashi commented
@adamslc thanks!

2021-04-20 02:07 UTC, merged